name: Controllo Bot Larry

on:
  workflow_dispatch:

jobs:
  run-my-code:
    runs-on: self-hosted
    steps:
      - name: Sincronizza i file
        uses: actions/checkout@v4

      - name: Installa librerie
        run: |
          python -m pip install --upgrade pip
          pip install pandas ccxt python-dotenv requests

      - name: Crea file .env dai Secrets
        run: |
          echo "KRAKEN_API_KEY=${{ secrets.KRAKEN_API_KEY }}" > Larry-Williams-Swing-Trading-Bot-V4/.env
          echo "KRAKEN_SECRET_KEY=${{ secrets.KRAKEN_SECRET_KEY }}" >> Larry-Williams-Swing-Trading-Bot-V4/.env
          # Aggiungi qui altri segreti se ne hai (es. TELEGRAM_TOKEN) seguendo lo stesso schema

      - name: Avvia il Bot
        run: |
          cd Larry-Williams-Swing-Trading-Bot-V4
          python kraken_bot_v4_advanced.py
