name: Controllo Bot Larry

on:
  workflow_dispatch:

jobs:
  run-my-code:
    runs-on: self-hosted
    steps:
      - name: Sincronizza i file
        uses: actions/checkout@v4

      - name: Avvia il Bot
        run: python main.py
