name: Controllo Bot Larry

on:
  workflow_dispatch:

jobs:
  run-my-code:
    runs-on: self-hosted
    steps:
      - name: Sincronizza i file
        uses: actions/checkout@v4

      - name: Debug - Mostra i file (se fallisce)
        run: dir /s

      - name: Installa librerie
        run: |
          python -m pip install --upgrade pip
          pip install pandas ccxt python-dotenv requests 
          # Ho aggiunto le librerie standard dei bot di trading per sicurezza

      - name: Avvia il Bot
        run: |
          cd Larry-Williams-Swing-Trading-Bot-V4
          python kraken_bot_v4_advanced.py
