name: Controllo Bot Larry

on:
  workflow_dispatch:

jobs:
  run-my-code:
    runs-on: self-hosted
    steps:
      - name: Sincronizza i file
        uses: actions/checkout@v4

      - name: Installa dipendenze
        run: |
          python -m pip install --upgrade pip
          pip install -r Larry-Williams-Swing-Trading-Bot-V4/requirements.txt

      - name: Avvia il Bot
        run: |
          cd Larry-Williams-Swing-Trading-Bot-V4
          python kraken_bot_v4_advanced.py
